const express = require('express')
const app = express()
const port = 3000
const bodyParser=require('body-parser')
const jsonParser=bodyParser.json();

let users=[
    {   name: 'Dzmitri Antonenko',
        firstName:'Dzmitri',
        lastName: 'Antonenko',
        id: '1',
        fullName: 'Дмитрий Алексеевич Антоненко',
        mainName:'Дмитрий Антоненко',
        mainName:'Дмитрий Антоненко',
        mainFirstName:'Димтрий',
        mainMiddleName: "Анатольевич",
        mainLastName: "Антоненко",
        avatar: '../src/images/avatars/avatar-man-1.svg',
        department: 'Web & Mobile',
        room: '1608',
        mobile: '+375 29 1234567',
        homePhone: '123',
        randomNumber: 'С5400001',
        email: "mdzimtri@lvrx.com",
        password: '111',
        skype: 'dzmitri.antonenko',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        gender: 'Mr',
        access: 'User',
        vacation: 'Disabled',
        redesign: 'Enabled'},
    {name: 'Aleh Zhukau',
        firstName:'Aleh',
        lastName: 'Zhukau',
        id: "2",
        mainName:'Олег Жуков',
        fullName: 'Олег Петрович Жуков',
        mainFirstName:'Олег',
        mainMiddleName: "Петрович",
        mainLastName: "Жуков",
        avatar: '../src/images/avatars/avatar-man-2.svg',
        department: 'Web & Mobile',
        room: '1635',
        homePhone: '123',
        mobile: '+333 333 33345',
        randomNumber: 'С5400001',
        email: "alen@lvrx.com",
        password: '222',
        skype: 'alen.zhukau',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        gender: 'Mr',
        access: 'User',
        vacation: 'Enabled',
        redesign: 'Enabled'},
    {name: 'Maksim Podolsky',
        firstName:'Maksim',
        lastName: 'Podolsky',
        mainName:'Максим Подольский',
        fullName: 'Максим Максимович Подольский',
        mainFirstName:'Максим',
        mainMiddleName: "Максимович",
        mainLastName: "Подольский",
        id: '3',
        avatar: '../src/images/avatars/avatar-man-3.svg',
        department: 'Web & Mobile',
        mobile: '+375 33 3334589',
        room: '1628',
        homePhone: '123',
        randomNumber: 'С5400001',
        email: "maksim@lvrx.com",
        password: '333',
        skype: 'maksim.podolski',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        gender: 'Mr',
        access: 'User',
        vacation: 'Disabled',
        redesign: 'Enabled'},
    {name: 'Vitaliy Vlasov',
        firstName:'Vitaliy',
        lastName: 'Vlasov',
        mainName:'Виталий Власов',
        fullName: 'Виталий Петрович Власов',
        mainFirstName:'Виталий',
        mainMiddleName: "Петрович",
        mainLastName: "Власов",
        id: '4',
        avatar: '../src/images/avatars/avatar-man-4.svg',
        department: 'Web & Mobile',
        room: '1628',
        homePhone: '123',
        mobile: '+375 25 4444444',
        randomNumber: 'С5400001',
        email: "vlasov@lvrx.com",
        password: '444',
        skype: 'vitali.vlasov',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        access: 'User',
        gender: 'Mr',
        vacation: 'Enabled',
        redesign: 'Enabled'},
    {name: 'Anna Belova',
        firstName:'Anna',
        lastName: 'Belova',
        mainName:'Анна Белова',
        fullName: 'Анна Аристарховна Белова',
        mainFirstName:'Анна',
        mainMiddleName: "Аристарховна",
        mainLastName: "Белова",
        id: '5',
        avatar: '../src/images/avatars/avatar1.svg',
        department: 'Web & Mobile',
        room: '1628',
        homePhone: '123',
        mobile: '+375 22 6666666',
        randomNumber: 'С5400001',
        email: "belova@lvrx.com",
        password: '555',
        skype: 'anna.belova',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        access: 'User',
        gender: 'Ms',
        vacation: 'Enabled',
        redesign: 'Enabled'},
    {name: 'Bella Markova',
        firstName:'Bella',
        lastName: 'Markova',
        mainName:'Белла Маркова',
        fullName: 'Белла Леонидовна Маркова',
        mainFirstName:'Белла',
        mainMiddleName: "Леонидовна",
        mainLastName: "Маркова",
        id: '6',
        avatar: '../src/images/avatars/avatar2.svg',
        department: 'Web & Mobile',
        room: '1628',
        homePhone: '123',
        mobile: '+375 31 9876543',
        randomNumber: 'С5400001',
        email: "bella@lvrx.com",
        password: '666',
        skype: 'bella.markova',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        access: 'Editor',
        gender: 'Ms',
        vacation: 'Enabled',
        redesign: 'Enabled'},
    {name: 'Karina Blogova',
        firstName:'Karina',
        lastName: 'Blogova',
        id: '7',
        mainName:'Карина Блогова',
        fullName: 'Карина Вячеславовна Блогова',
        mainFirstName:'Карина',
        mainMiddleName: "Вячеславовна",
        mainLastName: "Блогова",
        avatar: '../src/images/avatars/avatar3.svg',
        department: 'Web & Mobile',
        room: '1628',
        homePhone: '123',
        mobile: '+375 25 2552552',
        randomNumber: 'С5400001',
        email: "blogova@lvrx.com",
        password: '777',
        skype: 'karina.blogova',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        gender: 'Ms',
        access: 'Editor',
        vacation: 'Enabled',
        redesign: 'Enabled'},
    {name: 'Jadene Carver',
        firstName:'Jadene',
        lastName: 'Carver',
        id: '8',
        mainName:'Жадин Карвер',
        fullName: 'Жадин Алексеевна Карвер',
        mainFirstName:'Жадин',
        mainMiddleName: "Алексеевна",
        mainLastName: "Карвер",
        avatar: '../src/images/avatars/avatar4.svg',
        department: 'Web & Mobile',
        room: '1628',
        homePhone: '123',
        mobile: '+375 84 7542911',
        randomNumber: 'С5400001',
        email: "carver@lvrx.com",
        password: '888',
        skype: 'jadene.rarver',
        date: new Date().toLocaleDateString('en-GB',{day: 'numeric', month: 'long', year: 'numeric'}),
        status: "Active",
        access: 'Admin',
        gender: 'Ms',
        vacation: 'Enabled',
        redesign: 'Enabled'
        }
]

JSON.stringify(users)

app.use((req,res,next)=>{
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers','*');
    res.header('Access-Control-Allow-Methods','GET,POST,PUT');
    res.header('Access-Control-Allow-Credentials','true');
    next();
})
app.get('/users', (req, res) => {
    res.send(users)
})

app.put('/users',jsonParser,function(req,res){
    if(req.body){
        console.log(req.body)
        users=req.body;
        res.send(users)
    }


})


app.listen(port, () => {
console.log('da')
})